/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Seasons */
        get: operations["list_seasons_api_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team-seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team Seasons */
        get: operations["team_seasons_api_team_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairs/{pair_id}/table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pair Table */
        get: operations["pair_table_api_pairs__pair_id__table_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/curves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Curves */
        get: operations["curves_api_curves_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict */
        post: operations["predict_api_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        /** Create Scenario */
        post: operations["create_scenario_api_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Scenario */
        put: operations["update_scenario_api_scenarios__scenario_id__put"];
        post?: never;
        /** Delete Scenario */
        delete: operations["delete_scenario_api_scenarios__scenario_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessTokenOut */
        AccessTokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /** Expires In */
            expires_in: number;
        };
        /** CurvesOut */
        CurvesOut: {
            /**
             * Metric
             * @enum {string}
             */
            metric: "xg" | "xgd" | "gd" | "points";
            /**
             * Method
             * @enum {string}
             */
            method: "pooled" | "per_season";
            /** N Observations */
            n_observations: number;
            /** N Pairs */
            n_pairs: number;
            /** Games */
            games: number[];
            prior: components["schemas"]["FitOut"];
            /** Current Rmse */
            current_rmse: number[];
            /** Current Mae */
            current_mae: number[];
            /** Current R2 */
            current_r2: number[];
            /** Loso Rmse */
            loso_rmse: number[] | null;
            /** Crossover */
            crossover: number | null;
            /** Crossover Loso */
            crossover_loso: number | null;
        };
        /** FitOut */
        FitOut: {
            /** Rmse */
            rmse: number;
            /** Mae */
            mae: number;
            /** R2 */
            r2: number;
            /** N */
            n: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** PairTableOut */
        PairTableOut: {
            /** Pair Id */
            pair_id: number;
            /** Games */
            games: number;
            /** Rows */
            rows: components["schemas"]["TableRow"][];
        };
        /** PredictOut */
        PredictOut: {
            /**
             * Metric
             * @enum {string}
             */
            metric: "xg" | "xgd" | "gd" | "points";
            /** Games */
            games: number;
            /** Prior Weight */
            prior_weight: number;
            /** Obs Variance */
            obs_variance: number;
            prior: components["schemas"]["FitOut"];
            current: components["schemas"]["FitOut"];
            /** Blended Rmse */
            blended_rmse: number;
            /** Blended Mae */
            blended_mae: number;
            /** Weight Prior */
            weight_prior: number;
            /** Weight Data */
            weight_data: number;
        };
        /** PredictRequest */
        PredictRequest: {
            /**
             * Metric
             * @enum {string}
             */
            metric: "xg" | "xgd" | "gd" | "points";
            /** Games */
            games: number;
            /**
             * Prior Weight
             * @default 5
             */
            prior_weight: number;
            /**
             * Obs Variance
             * @default 1.5
             */
            obs_variance: number;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** ScenarioCreate */
        ScenarioCreate: {
            /** Name */
            name: string;
            params: components["schemas"]["ScenarioParams"];
        };
        /** ScenarioOut */
        ScenarioOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            params: components["schemas"]["ScenarioParams"];
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ScenarioParams */
        ScenarioParams: {
            /**
             * Metric
             * @enum {string}
             */
            metric: "xg" | "xgd" | "gd" | "points";
            /**
             * Method
             * @default pooled
             * @enum {string}
             */
            method: "pooled" | "per_season";
            /**
             * Prior Weight
             * @default 5
             */
            prior_weight: number;
            /**
             * Obs Variance
             * @default 1.5
             */
            obs_variance: number;
        };
        /** ScenarioUpdate */
        ScenarioUpdate: {
            /** Name */
            name?: string | null;
            params?: components["schemas"]["ScenarioParams"] | null;
        };
        /** SeasonPairOut */
        SeasonPairOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Prior Season */
            prior_season: string;
            /** Current Season */
            current_season: string;
            /** Common Team Count */
            common_team_count: number;
            /** Season Start */
            season_start: string;
            /** Season End */
            season_end: string;
        };
        /** TableRow */
        TableRow: {
            /** Team Id */
            team_id: number;
            /** Name */
            name: string;
            /** Games Played */
            games_played: number;
            /** Wins */
            wins: number;
            /** Draws */
            draws: number;
            /** Losses */
            losses: number;
            /** Goals For */
            goals_for: number;
            /** Goals Against */
            goals_against: number;
            /** Goal Diff */
            goal_diff: number;
            /** Points */
            points: number;
            /** Xg */
            xg: number;
            /** Xga */
            xga: number;
            /** Xgd */
            xgd: number;
            /** Live Rank */
            live_rank: number | null;
            /** In Pair */
            in_pair: boolean;
            /** Final Rank */
            final_rank: number | null;
        };
        /** TeamOut */
        TeamOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Seasons */
            seasons: components["schemas"]["TeamSeasonOut"][];
        };
        /** TeamSeasonOut */
        TeamSeasonOut: {
            /** Pairid */
            pairId: number;
            /** Season */
            season: string;
            /** Finalrank */
            finalRank: number;
            /** Points */
            points: number;
            /** Gd */
            gd: number;
            /** Xg */
            xg: number;
            /** Xga */
            xga: number;
            /** Xgd */
            xgd: number;
            /** Inpair */
            inPair: boolean;
            /** Rankbygame */
            rankByGame: number[];
        };
        /** TeamSeasonsOut */
        TeamSeasonsOut: {
            /** Teams */
            teams: components["schemas"]["TeamOut"][];
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_seasons_api_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonPairOut"][];
                };
            };
        };
    };
    team_seasons_api_team_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamSeasonsOut"];
                };
            };
        };
    };
    pair_table_api_pairs__pair_id__table_get: {
        parameters: {
            query: {
                games: number;
            };
            header?: never;
            path: {
                pair_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairTableOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    curves_api_curves_get: {
        parameters: {
            query: {
                metric: "xg" | "xgd" | "gd" | "points";
                method?: "pooled" | "per_season";
                pair_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurvesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_api_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenOut"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioOut"][];
                };
            };
        };
    };
    create_scenario_api_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_scenario_api_scenarios__scenario_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scenario_api_scenarios__scenario_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
